<img src="https://shwetkm.github.io/upxlogo.png"></img>

# Python Advanced - Data Science Foundation

**SET THE WORKING DIRECTORY SO THAT WE DO NOT HAVE TO THINK ABOUT PATH PROBLEMS**

Please ensure all your folder names <font color='red'><b>do not have a space & use forward slash (/)</b></font>

In [1]:
# Please ensure the path follows the rules we had discussed and ensure a '/' at the last
your_local_path="C:/Users/tejks/Desktop/ML/practice/"

In [2]:
def func_python(N):
    d=0
    for i in range(N):
        d += (i % 3 - 1) * i
    return d

In [3]:
%timeit func_python(10000)

100 loops, best of 3: 1.74 ms per loop


In [4]:
distance = [45,50,35]
speed = [5,10,7]


time = distance/speed 
print (time)

TypeError: unsupported operand type(s) for /: 'list' and 'list'

**Introduction to NumPy**

NumPy (short form for Numerical Python) is the most fundamental package designed for scientific computing and data analysis. Most of the other packages such as pandas, statsmodels are built on top of it, and is an important package to know and learn about. At the heart of NumPy is a data structure called **ndarray**. ndarray is a basically a multi-dimensional array that is built specifically for the purpose of numerical data analysis. Python also has array capabilities, but they are more generic. <b>The advantage of using ndarray is that processing is extremely efficient and fast.</b> 

You can perform standard mathematical operations on either individual elements or complete array. The range of functions covered is <b>linear algebra, statistical operations, and other specialized mathematical operations</b>. For our purpose, we need to know about <b>ndarray and the range of mathematical functions that are relevant to our research purpose</b>. If you already know languages such as C, Fortran, then you can integrate NumPy code with code written in these languages and can pass NumPy arrays seamlessly. 

From an overall perspective, understanding of <b>NumPy will help us in using pandas effectively as it is built on top of NumPy and frequently we will also be using functions of NumPy in research work</b>. In the current session, we will only look at some of the most important features of NumPy. For a full listing of NumPy features, please visit http://wiki.scipy.org/Numpy_Example_List .

Possible application of NumPy package in research work are:
<i>
+ Algorithmic operations such as sorting, grouping and set operations
+ Performing repetitive operations on whole arrays of data without using loops
+ Data merging and alignment operations
+ Data indexing, filtering, and transformation on individual elements or whole arrays
+ Data summarization and descriptive statistics
</i>
**Installing NumPy**

In order to check if NumPy is installed, go to Package Manager and type NumPy. You will get a list of packages with names closely matching to NumPy. For our purpose, we need to focus on package named numpy 1.xx. If the package is not installed, click on Install. 

**Importing NumPy**

In order to be able to use NumPy, first import it using import statement

In [6]:
import numpy as np

The above statement will import all of NumPy into your workspace. For starters its good, but if you are doing performance intensive work, then saving space is of importance. In such cases, you can import specific modules of NumPy by using

In [27]:
from numpy import array
from numpy import arange

In [26]:
# How we have overcome the prior challenge using 
dist = array(distance)
spd = np.array(speed)
print (dist)
print (spd)
time= dist/spd
print (time)
len(time)

[45 50 35]
[ 5 10  7]
[ 9.  5.  5.]


3

ndarray
The most important data structure in NumPy is an n-dimensional array object. Using ndarray, you can store large multidimensional datasets in Python. Being an array, you can <b>perform mathematical operations on these arrays either one element at a time or on complete arrays without using loops</b>. The way to initialize an array object is

In [11]:
a=[1,2,3,4,5]                                 # initialize a list and assign values to it
b=[10,20,30,40,50]
print (a + b)
#print (a + 5)                               #Want to add '5' to all the elements in the list
c = [val + 5 for val in a]           
print (c)

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]
[6, 7, 8, 9, 10]


In [17]:
a = array((1,2,3,4,5))                       # initializes an array a and assigns values to it
b = array((10,20,30,40,50))                  # initializes another array b
#print (a)
#print (b)
print(a+b) 
print (a+5) 
a**2
b**3

[11 22 33 44 55]
[ 6  7  8  9 10]


array([  1000,   8000,  27000,  64000, 125000], dtype=int32)

In [28]:
c = array(arange(10))                           #arange function here works as a sequence or counter in increments of 1
print ('array:                ', c)
print()
print()

anarray = array(np.arange(5,56,5))                 #arange function here works as a sequence or counter in increments of 5
print ('anarray:              ', anarray)
print()
print()

onemorearray = array(np.linspace(3.4,4,11.7))           #linspace function here creates 11 evenly spaced numbers over a specified interval
print ('onemorearray:         ', onemorearray)
print ('Rounded onemorearray: ', np.round(onemorearray,0))
onemorearray.sum()

array:                 [0 1 2 3 4 5 6 7 8 9]


anarray:               [ 5 10 15 20 25 30 35 40 45 50 55]


onemorearray:          [ 3.4   3.46  3.52  3.58  3.64  3.7   3.76  3.82  3.88  3.94  4.  ]
Rounded onemorearray:  [ 3.  3.  4.  4.  4.  4.  4.  4.  4.  4.  4.]


40.699999999999996

With each ndarray are associated two attributes: shape of the array, and type of the array. The <font color='red'><b>shape</b> of the array tells you about <b><u>dimensionality</u></b> of the array (rows and columns), and <b>type</b> of the array tells you about the <b><u>data type</u></b> contained</font> in the array.

In [36]:
data = np.array((32,45,123,756,23,2123,1,2,3,4,5,6,6,5,4,3,2,1,78,89,87,76,54,31))
data = data.reshape(8,3)
data2 = data.reshape(2,3,2,2)
print(data)
print ("*****")
print (data2)
print(data2.shape)
print(data2.dtype)
print(data2.size)
#even_data = (data % 2 == 0)
#data[even_data]

[[  32   45  123]
 [ 756   23 2123]
 [   1    2    3]
 [   4    5    6]
 [   6    5    4]
 [   3    2    1]
 [  78   89   87]
 [  76   54   31]]
*****
[[[[  32   45]
   [ 123  756]]

  [[  23 2123]
   [   1    2]]

  [[   3    4]
   [   5    6]]]


 [[[   6    5]
   [   4    3]]

  [[   2    1]
   [  78   89]]

  [[  87   76]
   [  54   31]]]]
(2, 3, 2, 2)
int32
24


In [37]:
np.zeros(50) + 5                        # Make a 50, 0 numbered single dimensional array

array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,
        5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,
        5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,
        5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])

In [40]:
np.zeros((3,5)) + 6                     # Make a 15, 0 numbered 2 dimensional array

array([[ 6.,  6.,  6.,  6.,  6.],
       [ 6.,  6.,  6.,  6.,  6.],
       [ 6.,  6.,  6.,  6.,  6.]])

In [41]:
np.ones(30) + 7                         # Make a 30, 1 numbered single dimensional array

array([ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,
        8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,
        8.,  8.,  8.,  8.])

In [42]:
np.ones((5,9))                       # Make a 45, 1 numbered 2 dimensional array

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [43]:
np.eye(5)                            # creates a 5*5 identity matrix. 

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [44]:
np.diag(array([1,3,5,3,4,5]))        # Populate the disgonal elements only

array([[1, 0, 0, 0, 0, 0],
       [0, 3, 0, 0, 0, 0],
       [0, 0, 5, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 5]])

**pandas**

Pandas is the primary package for performing data analysis tasks in Python. pandas derives its name from <b>PANel Data AnalysiS</b> and is the fundamental package that provides <b>relational data structures (think Excel, SQL type) and a host of capabilities to play with those data structures</b>. It is the most widely used package in Python for data analysis tasks, and is very good to work with <b>cross sectional, time series, and panel data analysis</b>. Python sits on top of NumPy and can be used with NumPy arrays and the functions in NumPy. How is pandas suited for a researcher’s needs:
<i>
+ Has a tabular data structure that can hold both <b>homogenous and heterogenous data</b>.
+ Very <b>good indexing capabilities</b> that makes data alignment and merging easy.
+ Good <b>time series functionality</b>. No need to use different data structures for time series and cross sectional data. Allows for both <b>ordered and unordered time-series data</b>.
+ A host of <b>statistical functions</b> developed around NumPy and pandas that makes a researcher’s task easy and fast.
+ Programming is lot <b>simpler and faster</b>.
+ Easily handles <b>data manipulation and cleaning</b>.
+ Easy to expand and shorten data sets. <b>Comprehensive merging, joins, and group by functionality to join multiple data sets</b>.
</i>

**Installing pandas** 

In order to check if pandas is installed, go to Package Manager and type pandas. By default, pandas already comes installed with a distribution of Canopy. If the package is not installed, click on Install.

**Importing pandas**

In order to be able to use NumPy, first import it using import statement


In [45]:
import pandas as pd                         # This will import pandas into your workspace

In [47]:
import numpy as np                          # We will be using numpy functions so import numpy

**Data Structures in pandas**

There are two basic data structures in pandas: <b><i>Series and DataFrame</i></b>

**Series:** It is similar to a NumPy 1-dimensional array. In addition to the values that are specified by the programmer, <b>pandas attaches a label to each of the values</b>. If the labels are not provided by the programmer, then pandas assigns labels ( 0 for first element, 1 for second element and so on). A benefit of assigning labels to data values is that it becomes easier to perform manipulations on the dataset as the whole dataset becomes more of a dictionary where each value is associated with a label. 


In [48]:
series1 = pd.Series([10,20,30,40])
series1

0    10
1    20
2    30
3    40
dtype: int64

In [49]:
series1.values

array([10, 20, 30, 40], dtype=int64)

In [50]:
series1.index

RangeIndex(start=0, stop=4, step=1)

If you want to specify custom index values rather than the default ones provided, you can do so using the following command

In [53]:
series2 = pd.Series([10,20,30,40,50], index=['one','two','three','four','five'])
series2

one      10
two      20
three    30
four     40
five     50
dtype: int64

The ways of accesing elements in a Series object are similar to what we have seen in NumPy, and you can perform NumPy operations on Series data arrays.

In [55]:
series2[2]                  # How to print 30 from the series

30

In [54]:
series2['three']            # Another way to print 30 from the series

30

In [56]:
series2[['one', 'three', 'five']]

one      10
three    30
five     50
dtype: int64

In [57]:
series2[[0,1,3]]

one     10
two     20
four    40
dtype: int64

In [58]:
series2 + 4            # Add 4 to every element

one      14
two      24
three    34
four     44
five     54
dtype: int64

In [59]:
series2 ** 3           # Cube every element 

one        1000
two        8000
three     27000
four      64000
five     125000
dtype: int64

In [60]:
series2[series2>30]    # Find all values greater than 30

four    40
five    50
dtype: int64

In [61]:
np.sqrt(series2)       # Get the square roots of all the values

one      3.162278
two      4.472136
three    5.477226
four     6.324555
five     7.071068
dtype: float64

If you have a dictionary, you can <b>create a Series data structure from that dictionary</b>. Suppose you are interested in EPS values for firms and the <i>values come from different sources and is not clean. In that case you dont have to worry about cleaning and aligning those values</i>. 

In [ ]:
years = [90, 91, 92, 93, 94, 95]
f1 = {90:8, 91:9, 92:7, 93:8, 94:9, 95:11, 96:13}
firm1 = pd.Series(f1,index=years)                     # Extra element in VALUE not an issue
firm1

In [ ]:
f2 = {90:14,92:9, 93:13, 94:5}                      
firm2 = pd.Series(f2,index=years)                   # Extra element in the KEY is handled as NaN
firm2

In [ ]:
f3 = {93:10, 94:12, 95: 13}
firm3 = pd.Series(f3,index=years)
firm3

NaN stands for missing or NA values in pandas. Make use of isnull() function to find out if there are any missing values in the data structure.

In [ ]:
pd.isnull(firm3)

A key feature of Series data is structures is that you don't have to worry about data alignment. For example, if we have run a word count program on two different files and we have the following data structures

In [ ]:
dict1 = {'finance': 10, 'earning': 5, 'debt':8}
dict2 = {'finance' : 8, 'compensation':4, 'earning': 9}
count1 = pd.Series(dict1)
count2 = pd.Series(dict2)
print (count1)
print (count2)

If we want to calculate the sum of common words in combined files, then we dont have to worry about data alignment. If we want to include all words, then we can take care of NaN values and compute the sum. By default, Series data structure ignores NaN values. NaN values stand for missing data values.

In [ ]:
count1+count2                                # Sum values on key based retrieval. Non matching keys become NaN

In [ ]:
data.ix[2]                              # Print the row corresponding to the given Index

In [ ]:
data.ix[data.ticker=='DIS']            # Print the row corresponding to the ticker that is 'DIS'

In order to add additional columns

In [ ]:
data['Year'] = 2014                       # Add additional column Year. Populate value of 2014 in all the rows.
data

In [ ]:
data['pricesquared'] = data.price**2      # Square all the prices and add another column 'pricesquared'.
data

In [ ]:
del data['pricesquared']                  # Delete column 'pricesquared'
data

In [ ]:
data['pricesquared'] = np.NaN             # Create column 'pricesquared' with NaN values
data

In [ ]:
data['sequence'] = np.arange(1,6)         # Add column 'sequence' and populate sequence of numbers from 1 to 5
data

In [ ]:
data.values                               # Get the values in a 2 dimensional form (without index)

In [ ]:
newdata = data.drop(2)                    # Delete data at index 2
newdata

In [ ]:
years = [90, 91, 92, 93, 94, 95]
print('-------------Firm 1------------')
f1 = {90:8, 91:9, 92:7, 93:8, 94:9, 95:11}
firm1 = pd.Series(f1,index=years)
print(firm1)
print('-------------Firm 2------------')
f2 = {90:14,92:9, 93:13, 94:5}
firm2 = pd.Series(f2,index=years)
print(firm2)
print('-------------Firm 3------------')
f3 = {93:10, 94:12, 95: 13}
firm3 = pd.Series(f3,index=years)
print(firm3)
print('-------------Create empty dataframe------------')
df1 = pd.DataFrame(columns=['Firm1','Firm2','Firm3'],index=years)    # Convert the 3 series to a DataFrame with 'years' as Index
print(df1)
print('-------------Populate the dataframe------------')
df1.Firm1 = firm1
df1.Firm2 = firm2
df1.Firm3 = firm3
print(df1)


In [ ]:
dft = df1.T         # Transpose the table
print(dft)
print('-----------------Delete Column = 90--------------------------')
del dft[90]
print(dft)


You can pass a number of data structures to DataFrame such as a <b>ndarray, lists, dict, Series, and another DataFrame</b>. You can also <b>reindex</b> to confirm to data to a new index. Reindexing is a powerful feature that <b>allows you to access data in a number of different ways</b>, and also to confirm data to some new time series or other index.

In [ ]:
reindexdf1 = df1.reindex([88,89,90,91,92,93,94,95,96,97,98])     # No data from 88-89 & from 96-98
reindexdf1

In [ ]:
print(df1)                                                 # Year from 90 to 95                
reindexdf1 = df1.reindex(np.arange(1988,2008))             # Make the years more meaningful. Then populate the values separately.
reindexdf1

In [ ]:
years1 = [90, 91, 92, 93, 94, 95]
print('-------------Firm 4------------')
f4 = {90:8, 91:9, 92:7, 93:8, 94:9, 95:11}
firm4 = pd.Series(f4,index=years)
print(firm4)
print('-------------Firm 5------------')
f5 = {90:14,91:12, 92:9, 93:13, 94:5, 95:8}
firm5 = pd.Series(f5,index=years)
print(firm5)
print('-------------Firm 6------------')
f6 = {90:8, 91: 9, 92:9,93:10, 94:12, 95: 13}
firm6 = pd.Series(f6,index=years)
print(firm6)
print('-------------Create  empty Data Frame------------')
df2 = pd.DataFrame(columns=['Firm1','Firm2','Firm3'],index=years1)
print(df2)
print('-------------Assign values to the Data Frame------------')
df2.Firm1 = firm4
df2.Firm2 = firm5
df2.Firm3 = firm6
print(df2)


In [ ]:
reindexdf2 = df2.reindex([88,89,90,91,92,93,94,95,96,97,98], fill_value=0)             # Fill row values with 0
reindexdf2

Similarly, you have backfill (bfill) method to fill values backwards.

In [ ]:
reindexdf3 = df2.reindex([88,89,90,91,92,93,94,95,96,97,98], method='ffill') # Forwrd fill the last non-empty row to the left over
reindexdf3

In [ ]:
reindexdf1

In [ ]:
reindexdf3

In [ ]:
reindexdf1+reindexdf3

In [ ]:
reindexdf1.add(reindexdf3, fill_value=0)                      # Replace values for non-existing element to 0 so as help sum up

You can use NumPy functions inside DataFrame objects.

In [ ]:
dataframe = pd.DataFrame(np.random.randn(3,3),columns=['one','two','three'])  # Create array of 3*3 dimensionality using standard normally distributed random vales
dataframe

In [ ]:
np.abs(dataframe)                   # Absolute value

In [ ]:
f = lambda x:x.max()-x.min()        # We have option to use a powerful lambda function feature. Get the range in a column
dataframe.apply(f)

In [ ]:
dataframe.apply(f,axis=1)           # Apply lambda function on the row and not column as we did in the previous example

In [ ]:
print(dataframe)
g = lambda x: x - np.mean(x)        
dataframe.apply(g)

In [ ]:
def f(x):
    return pd.Series([np.mean(x), x.max(), x.min()], index=['mean','max','min'])
print(dataframe)
dataframe.apply(f)

In [ ]:
dataframe = pd.DataFrame(np.random.randn(3,3),columns=['one','two','three'])
dataframe

In [ ]:
print(dataframe.sort_index(by='one'))    # Sort by column 'one'

In [ ]:
dataframe.sort_index(by=['one','two'])   # Sort first by column 'one' then by column 'two'

In [ ]:
dataframe.sum()                          # Column wise sum

In [ ]:
dataframe.sum(axis=1)                    # Row wise sum

In [ ]:
print(dataframe)
dataframe.cumsum(axis=1)                 # Get cumulative sum

In [ ]:
dataframe.describe()

If you have non-numeric data, then applying describe function would produce statistics such as <b>count, unique, frequency</b>. In addition to this, you can also calculate <b>skewness (skew), kurtosis (kurt), percent changes, difference, and other statistics</b>.

**Missing Data**

Pandas have a number of features to deal with <b>missing data</b>. We have seen an example of the case of descriptive statistics, where missing values are not taken into account while calculating the descriptive statistics. Missing data is denoted by NaN. 

In [ ]:
years = [90, 91, 92, 93, 94, 95]
f1 = {90:8, 91:9, 92:7, 93:8, 94:9, 95:11}
firm1 = pd.Series(f1,index=years)
firm1
f2 = {90:14,92:9, 93:13, 94:5}
firm2 = pd.Series(f2,index=years)
firm2
f3 = {93:10, 94:12, 95: 13}
firm3 = pd.Series(f3,index=years)
firm3
df3 = pd.DataFrame(columns=['Firm1','Firm2','Firm3'],index=years)
df3
df3.Firm1 = firm1
df3.Firm2 = firm2
df3.Firm3 = firm3
df3

In [ ]:
firm2

In [ ]:
nadeleted = firm2.dropna()
nadeleted

In [ ]:
df3

In case of DataFrame, <b>if you use dropna, it deletes entire row by default</b>. Another way is to drop only <b>those rows that are all NA</b>. If you want to <b>drop columns, pass axis=1</b>

In [ ]:
cleandf3 = df3.dropna()          # Drop row if any value in the row is NaN

In [ ]:
cleandf3

In [ ]:
clean2 = df3.dropna(how='all')   # Drop row if all values in the row are NaN
clean2

In [ ]:
columndrop = df3.dropna(axis=1)   # Drop column if any value in the column is NaN
columndrop

In [ ]:
df3

In [ ]:
thresholddf = df3.dropna(thresh=2)    # Define threshold. In this case row having >= 2 NaN, drop the row
thresholddf

In [ ]:
fillna1 = df3.fillna(0)      # Fill all NaN values with 0
fillna1

In [ ]:
fillna2 = df3.fillna({'Firm1':8, 'Firm2': 10, 'Firm3':14})   # We can specify what value should be replaced
fillna2

In [ ]:
df3

In [ ]:
fillna3 = df3.fillna(method='ffill')    # Forward fill NaNs for 1 level. Check Firm 2 -> 14 & 5
fillna3

In [ ]:
fillna4 = df3.fillna(method='bfill',limit=2)    # Back fill NaNs till 2 levels before. Check how Firm3 behaves
fillna4

In [ ]:
#print(df3.mean())
fillna5 = df3.fillna(df3.mean())  # We will substitute empty values with Mean of the Firm in concern
fillna5

**Hierarchical Indexing**

Hierarchical indexing allows you to have <b>index on an index (multiple index)</b>. It is an important feature of pandas using which you can <b>select subsets of data and perform independent analyses</b> on them. For example, suppose you have <b>firm prices data and the data is indexed by firm name</b>. On top of that, you can <b>index firms by industry</b>. Thus, industry becomes an index on top of firms. You can then perform analyses either on individual firm, or on group of firms in an industry, or on the whole dataset.

In [ ]:
h_i_data = pd.Series(np.random.randn(10),index=[['Ind1','Ind1','Ind1','Ind1','Ind2','Ind2','Ind2','Ind3','Ind3','Ind3'],
                                              [1,2,3,4,1,2,3,1,2,3]])
h_i_data

In [ ]:
h_i_data['Ind3']   # Looks like Dictionary of a Dictionary

In [ ]:
h_i_data['Ind1':'Ind3']

In [ ]:
h_i_data[['Ind1','Ind3']]

In [ ]:
h_i_data[:,3]   # 3rd sub index of main Index. We have 3 values.

In [ ]:
h_i_data[:,4]   # 3rd sub index of main Index. We have 1 value.

In [ ]:
h_i_data.unstack()        # Pivot a level of the index labels

In [ ]:
h_i_data.unstack().stack()

In [ ]:
h_i_data.sum()

In [ ]:
print(h_i_data)
h_i_data.sum(level=1)  # Sum based on level 1, e.g. -0.407952 + 0.976813 + -0.360328 = 0.208534 (Between Industries)

In [ ]:
h_i_data.sum(level=0)   # Sum based on Type of Industry (Within Industry)

In [ ]:
h_i_data

In [ ]:
# Panel represents wide format panel data, stored as 3-dimensional array -> ndarray (items x major x minor)
pdata = pd.Panel(dict((stk,web.get_data_yahoo(stk,start='6/1/2014',end='6/9/2014'))
                      for stk in ['AAPL','GOOG','MSFT','DIS']))
pdata

In [ ]:
pdata.ix[:,'6/1/2014':,'Low']

In [ ]:
stacked_pdata = pdata.to_frame()                     # A better way to present the data

In [ ]:
#stacked_pdata
stacked_pdata.head()

**IO in pandas**

In this section, we will focus on <b>I/O from text files, csv, excel, and sql files as well as getting data from web such as Yahoo! Finance</b>. Using functions in pandas, you can read data as a DataFrame object. 

**Reading a csv file**

In [ ]:
roedatacsv = pd.read_csv(your_local_path+'roedata.csv')
#roedatacsv
roedatacsv.head()

If the file does not have a header, then you can either let pandas assign default headers or you can specify custom headers. If you want industry name to be the index of DataFrame, you can achieve that.

In [ ]:
roedatacsv = pd.read_csv(your_local_path+'roedata.csv', index_col = 'Industry Name' )
roedatacsv.head()

In [ ]:
roedatacsv = pd.read_csv(your_local_path+'roedata.csv', usecols = ['Industry Name','ROE'] ) # Prints on columns that we Use here
roedatacsv.head()

In [ ]:
capm_dem_data = pd.read_table(your_local_path+'capm_dem.dat', delimiter=' ',header = None)
capm_dem_data.head()

In [ ]:
compustatdata = pd.read_csv(your_local_path+'compustat.csv', index_col = ['ggroup','gvkey'] )
compustatdata = compustatdata.sort_index(0,ascending=False)
compustatdata.head()

In [ ]:
crsp_data = pd.read_table(your_local_path+'crsp.output', sep='\s+',header = None)
crsp_data.head()

** Handling missing values**

Some types of missing values are automatically identified by pandas as NaN while importing the data. Those types are NA, NULL, -1.#IND. Additionally, you can also specify a list of missing values. 

In [ ]:
roemissing = pd.read_csv(your_local_path+'roemissing.csv', na_values=['Null',-999] )
roemissing

In [ ]:
roemissing = pd.read_csv(your_local_path+'roemissing.csv', na_values={'Number of firms':['NULL',-999],'ROE':['10000.00%']} )
roemissing

**Writing Data**

In [ ]:
roedata = pd.read_csv(your_local_path+'roedata.csv')
roedata.to_csv(your_local_path+'roedatawrite.csv')

In [ ]:
roedata = pd.read_csv(your_local_path+'roedata.csv')
roedata.to_csv(your_local_path+'roedatawrite2.csv', index=False, columns=['Industry Name','ROE']) # Index = 'False' & select your own columns

**Merging Data**
<p/>Resembles Joins in database

In [ ]:
import pandas as pd

In [ ]:
left_frame = pd.DataFrame({'key': range(5), 
                           'left_value': ['a', 'b', 'c', 'd', 'e']})
right_frame = pd.DataFrame({'key': range(2, 7), 
                           'right_value': ['f', 'g', 'h', 'i', 'j']})
print(left_frame)
print('\n')
print(right_frame)

In [ ]:
pd.merge(left_frame, right_frame, on='key', how='inner')

In [ ]:
pd.merge(left_frame, right_frame, on='key', how='left')

In [ ]:
pd.merge(left_frame, right_frame, on='key', how='right')

In [ ]:
pd.merge(left_frame, right_frame, on='key', how='outer')

In [ ]:
pd.concat([left_frame, right_frame])

In [ ]:
pd.concat([left_frame, right_frame], axis=1)