In [2]:
import numpy as np

### Create a vector with values ranging from 10 to 49

In [149]:
v = np.arange(10,50)
v[::-1]
# :: notations with subscript before and after are very useful in printing all elements from n onwards in any order

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

### Reverse a vector (first element becomes last)

In [22]:
v[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

### Create a 3x3 matrix with values ranging from 0 to 8

In [23]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Find indices of non-zero elements from [1,2,0,0,4,0]

In [30]:
n = np.array([1,2,0,0,4,0])
n.nonzero()  #indices of non-zero elements

(array([0, 1, 4], dtype=int64),)

    ### Create a 3x3x3 array with random values

In [38]:
np.random.random_sample(size=(3,3,3))

array([[[ 0.41357567,  0.58935134,  0.10120987],
        [ 0.05097967,  0.50526008,  0.37932119],
        [ 0.14163966,  0.69627713,  0.53545301]],

       [[ 0.30153236,  0.84130758,  0.49372998],
        [ 0.1366344 ,  0.03140299,  0.75741601],
        [ 0.31929415,  0.53113561,  0.86266192]],

       [[ 0.16547818,  0.05642705,  0.18416192],
        [ 0.81039501,  0.83685006,  0.82385331],
        [ 0.58533466,  0.46936189,  0.17962306]]])

### Create a 10x10 array with random values and find the minimum and maximum values

In [40]:
n = np.random.random_sample(size=(10,10))
(n.min(), n.max())

(0.0068481259306880649, 0.9872693928208347)

### Create a 5x5 matrix with row values ranging from 0 to 4

In [49]:
n = np.arange(0,5).repeat(5, axis=0).reshape(5,5)
n

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

### Consider two random array A and B, check if they are equal

In [52]:
n = np.random.randint(0,100,size=(3,3))
m = np.random.randint(0,100,size=(3,3))
m == n

array([[False, False, False],
       [False, False, False],
       [False, False, False]], dtype=bool)

### find the closest value (to a given scalar) in a vector

In [65]:
v = np.random.randint(0,50,size=(6,6))
print(v)

[[10 14  2 12  6 46]
 [33 44 43 40 40 27]
 [39 36  0 14 24 42]
 [28 42  9  3 17 44]
 [26 35 29 32 12  0]
 [11 18 19 15 48 13]]


In [80]:
idx = np.unravel_index((np.abs(v-9.1)).argmin(), (6,6))
v[idx[0]][idx[1]]

9

### Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [116]:
import itertools
v = np.arange(1,6)

v1=list(itertools.chain.from_iterable([np.insert(np.zeros(3).astype(int),0,np.arange(1,6)[i]) for i in range(0,v.size)]))
v1

[1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5, 0, 0, 0]

### How to find the most frequent value in an array?

In [146]:
v2 = [4,3,2,3,3,3,3,3,3,6,6,6,6,5,34,3,2,0,0,1,2,2,2]
v3 = np.array(sorted(v2))
np.bincount(v2).max() #could have been used as well
(elems, counts) = np.unique(v2, return_counts=True)
elems[counts.argmax()]

3